#!/bin/sh

nohup ./split 0 &
nohup ./split 1 &
nohup ./split 2 &
nohup ./split 3 &
nohup ./split 4 &
nohup ./split 5 &
nohup ./split 6 &
nohup ./split 7 &
nohup ./split 8 &
nohup ./split 9 &
nohup ./split 10 &
nohup ./split 11 &
nohup ./split 12 &
nohup ./split 13 &
nohup ./split 14 &
nohup ./split 15 &
nohup ./split 16 &
nohup ./split 17 &
nohup ./split 18 &
nohup ./split 19 &
nohup ./split 20 &
nohup ./split 21 &
nohup ./split 22 &
nohup ./split 23 &
nohup ./split 24 &
nohup ./split 25 &
nohup ./split 26 &
nohup ./split 27 &
nohup ./split 28 &
nohup ./split 29 &
nohup ./split 30 &
nohup ./split 31 &
nohup ./split 32 &
